#!/bin/sh

set -e

xrandr_output=$(xrandr --current)
eDP=$(echo "$xrandr_output" | grep " connected " | grep eDP | cut -d " " -f 1)
HDMI=$(echo "$xrandr_output"  | grep " connected " | grep HDMI | cut -d " " -f 1)

if [ -z "$HDMI" ]
then
	xrandr --output "$eDP" --auto --primary
	echo only eDP
else
	xrandr	--output "$eDP" --mode 1920x1080 --scale 1.0 --pos 0x0 \
			--output "$HDMI" --mode 3840x2160 --scale 0.7 --primary --pos 1920x1080
	echo eDP with HDMI

	i3-msg focus output primary
	i3-msg focus output next
	i3-msg workspace "0:Zero"
	i3-msg focus output next
	i3-msg workspace "1:I: Melina"
fi

notify-send "i3-wm" "workspace configured"
