#!/bin/sh

touchpad_id=$(xinput --list | rg TouchPad | cut -f 2 | cut -d "=" -f 2)
echo touchpad id: $touchpad_id
tapping_id=$(xinput --list-props $touchpad_id | grep "Speed (" | cut -f 2 | cut -d "(" -f 2 | cut -d ")" -f 1)
xinput set-prop $touchpad_id $tapping_id 0.5
notify-send "i3-wm" "touchpad configured"
